# Generated by Django 5.2.8 on 2026-03-03 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cv_fichier', models.FileField(upload_to='cv/')),
                ('cv_texte', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'candidat',
            },
        ),
        migrations.CreateModel(
            name='FicheDePoste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Missions, responsabilités, contexte.')),
                ('competences_clees', models.TextField(blank=True, help_text='Compétences clés (séparées par des virgules).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fiche_de_poste',
            },
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True)),
                ('explication', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('retenue', 'Retenue'), ('refus', 'Refus')], default='nouvelle', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='recrutement.candidat')),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='recrutement.fichedeposte')),
            ],
            options={
                'db_table': 'candidature',
                'ordering': ['-score', '-created_at'],
                'unique_together': {('fiche', 'candidat')},
            },
        ),
    ]
