# Generated by Django 5.2.8 on 2026-03-03 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('invoices', '0001_initial'),
        ('technique', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Metier',
            fields=[
                ('nom', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'metier',
            },
        ),
        migrations.CreateModel(
            name='DefaultTempsRelance',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('temps', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'default_temps_relance',
            },
        ),
        migrations.CreateModel(
            name='OAuthToken',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='oauth_token', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('provider', models.CharField(default='google', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_expiry', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Token OAuth',
                'verbose_name_plural': 'Tokens OAuth',
                'db_table': 'oauth_tokens',
            },
        ),
        migrations.CreateModel(
            name='Pole',
            fields=[
                ('nom', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pole',
            },
        ),
        migrations.CreateModel(
            name='TempsRelance',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('temps', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'temps_relance',
            },
        ),
        migrations.CreateModel(
            name='TypeActivite',
            fields=[
                ('type', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'type_activite',
            },
        ),
        migrations.CreateModel(
            name='DefaultModeleRelance',
            fields=[
                ('metier', models.OneToOneField(db_column='metier', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='management.metier')),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'default_modele_relance',
            },
        ),
        migrations.CreateModel(
            name='EmailClient',
            fields=[
                ('pk', models.CompositePrimaryKey('contact', 'email', blank=True, editable=False, primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('contact', models.ForeignKey(db_column='contact', on_delete=django.db.models.deletion.CASCADE, to='invoices.contact')),
                ('metier', models.ForeignKey(db_column='metier', on_delete=django.db.models.deletion.CASCADE, to='management.metier')),
            ],
            options={
                'db_table': 'email_client',
            },
        ),
        migrations.CreateModel(
            name='ModeleRelance',
            fields=[
                ('pk', models.CompositePrimaryKey('utilisateur', 'metier', blank=True, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('metier', models.ForeignKey(db_column='metier', on_delete=django.db.models.deletion.CASCADE, to='management.metier')),
                ('utilisateur', models.ForeignKey(db_column='utilisateur', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'modele_relance',
            },
        ),
        migrations.CreateModel(
            name='TelClient',
            fields=[
                ('pk', models.CompositePrimaryKey('contact', 'tel', blank=True, editable=False, primary_key=True, serialize=False)),
                ('tel', models.TextField()),
                ('contact', models.ForeignKey(db_column='contact', on_delete=django.db.models.deletion.CASCADE, to='invoices.contact')),
            ],
            options={
                'db_table': 'tel_client',
            },
        ),
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('date_type', models.TextField(choices=[('echeance', 'Échéance'), ('date', 'Date')], default='echeance')),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('dossier', models.ForeignKey(db_column='dossier', on_delete=django.db.models.deletion.CASCADE, to='technique.technicalproject')),
                ('type', models.ForeignKey(db_column='type', on_delete=django.db.models.deletion.CASCADE, to='management.typeactivite')),
            ],
            options={
                'db_table': 'activite',
                'ordering': ['date'],
            },
        ),
    ]
