# Generated by Django 5.2.8 on 2026-05-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_module1_admin_improvements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='client',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='activite',
            name='contact_externe',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='activite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='activite',
            name='outlook_event_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='activite',
            name='titre',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='activite',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
