# Generated by Django 5.2.8 on 2026-06-18 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_dossier_administratif_foundation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activite',
            name='client',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='contact_externe',
        ),
    ]
