# Generated by Django 5.2.8 on 2026-03-25 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('technique', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActeurExterne',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'acteur_externe',
            },
        ),
        migrations.CreateModel(
            name='RelanceFournisseur',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('temps', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'relance_fournisseur',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.OneToOneField(
                    db_column='id',
                    on_delete=django.db.models.deletion.CASCADE,
                    primary_key=True,
                    serialize=False,
                    to='invoices.acteurexterne'
                )),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.OneToOneField(
                    db_column='id',
                    on_delete=django.db.models.deletion.CASCADE,
                    primary_key=True,
                    serialize=False,
                    to='invoices.acteurexterne'
                )),
                ('nom', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fournisseur',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('nom', models.TextField(blank=True, null=True)),
                ('prenom', models.TextField(blank=True, null=True)),
                ('acteur', models.ForeignKey(
                    db_column='acteur',
                    on_delete=django.db.models.deletion.CASCADE,
                    to='invoices.acteurexterne'
                )),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='EmailFournisseur',
            fields=[
                ('pk', models.CompositePrimaryKey(
                    'contact', 'email',
                    blank=True,
                    editable=False,
                    primary_key=True,
                    serialize=False
                )),
                ('email', models.TextField()),
                ('contact', models.ForeignKey(
                    db_column='contact',
                    on_delete=django.db.models.deletion.CASCADE,
                    to='invoices.contact'
                )),
            ],
            options={
                'db_table': 'email_fournisseur',
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('montant', models.FloatField(null=True)),
                ('statut', models.TextField(
                    choices=[
                        ('ongoing', 'En cours'),
                        ('received', 'Reçue'),
                        ('denied', 'Refusée'),
                        ('paid', 'Payée'),
                        ('archived', 'Archivée')
                    ],
                    default='ongoing'
                )),
                ('echeance', models.DateTimeField(blank=True, null=True)),
                ('titre', models.CharField(blank=True, max_length=255, null=True)),
                ('collaborateur', models.ForeignKey(
                    blank=True,
                    db_column='collaborateur_id',
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='factures',
                    to=settings.AUTH_USER_MODEL
                )),
                ('dossier', models.ForeignKey(
                    db_column='dossier',
                    on_delete=django.db.models.deletion.CASCADE,
                    to='technique.technicalproject'
                )),
                ('client', models.ForeignKey(
                    db_column='client',
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    to='invoices.client'
                )),
                ('fournisseur', models.ForeignKey(
                    db_column='fournisseur',
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    to='invoices.fournisseur'
                )),
            ],
            options={
                'db_table': 'facture',
            },
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='factures/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('facture', models.ForeignKey(
                    db_column='facture',
                    on_delete=django.db.models.deletion.CASCADE,
                    to='invoices.facture'
                )),
            ],
            options={
                'db_table': 'pieces_upload_local',
            },
        ),
        migrations.CreateModel(
            name='TelFournisseur',
            fields=[
                ('pk', models.CompositePrimaryKey(
                    'contact', 'tel',
                    blank=True,
                    editable=False,
                    primary_key=True,
                    serialize=False
                )),
                ('tel', models.TextField()),
                ('contact', models.ForeignKey(
                    db_column='contact',
                    on_delete=django.db.models.deletion.CASCADE,
                    to='invoices.contact'
                )),
            ],
            options={
                'db_table': 'tel_fournisseur',
            },
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.OneToOneField(
                    db_column='id',
                    on_delete=django.db.models.deletion.CASCADE,
                    primary_key=True,
                    serialize=False,
                    to='invoices.client'
                )),
                ('nom', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'entreprise',
            },
        ),
        migrations.CreateModel(
            name='Particulier',
            fields=[
                ('id', models.OneToOneField(
                    db_column='id',
                    on_delete=django.db.models.deletion.CASCADE,
                    primary_key=True,
                    serialize=False,
                    to='invoices.client'
                )),
                ('nom', models.TextField()),
                ('prenom', models.TextField()),
            ],
            options={
                'db_table': 'particulier',
            },
        ),
        migrations.CreateModel(
            name='ClientDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dossier', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='technique.technicalproject'
                )),
                ('client', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='invoices.client'
                )),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(fields=('client', 'dossier'), name='uniq_client_dossier')
                ],
            },
        ),
        migrations.CreateModel(
            name='FactureHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(
                    choices=[
                        ('status_change', 'Changement de statut'),
                        ('reminder_sent', 'Relance envoyée'),
                        ('user_action', 'Action utilisateur')
                    ],
                    max_length=30
                )),
                ('old_status', models.CharField(blank=True, max_length=50, null=True)),
                ('new_status', models.CharField(blank=True, max_length=50, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facture', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='historique',
                    to='invoices.facture',
                    verbose_name='Facture'
                )),
                ('user', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Utilisateur'
                )),
            ],
            options={
                'db_table': 'facture_historique',
                'ordering': ['-created_at'],
            },
        ),
    ]