# Generated by Codex on 2026-05-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="facture",
            name="service",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="facturehistorique",
            name="action",
            field=models.CharField(
                choices=[
                    ("status_change", "Changement de statut"),
                    ("reminder_sent", "Relance envoyée"),
                    ("reminder_skipped", "Relance ignorée"),
                    ("reminder_error", "Erreur de relance"),
                    ("user_action", "Action utilisateur"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="ExportCegidRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("success", "Succès"),
                            ("error", "Erreur"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("file", models.FileField(blank=True, null=True, upload_to="exports/cegid/")),
                ("line_count", models.PositiveIntegerField(default=0)),
                ("total_amount", models.FloatField(default=0)),
                ("anomaly_count", models.PositiveIntegerField(default=0)),
                ("warning_summary", models.TextField(blank=True, default="")),
                ("error_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cegid_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "export_cegid_run",
                "ordering": ["-started_at"],
            },
        ),
    ]
