# Generated by Django 5.2.8 on 2026-07-03 14:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def normalize_invoice_services(apps, schema_editor):
    Facture = apps.get_model('invoices', 'Facture')
    Facture.objects.filter(service__in=[
        'Comptabilité',
        'Comptabilite',
        'Comptabilité et Finance',
        'Comptabilite et Finance',
        'Finance',
        'finance',
    ]).update(service='financier')


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_gmail_invoice_reminders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='affaire',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Affaire concernée'),
        ),
        migrations.AddField(
            model_name='facture',
            name='commentaire_compta',
            field=models.TextField(blank=True, default='', verbose_name='Commentaire pour la compta'),
        ),
        migrations.AddField(
            model_name='facture',
            name='date_facture',
            field=models.DateField(blank=True, null=True, verbose_name='Date de facture'),
        ),
        migrations.AddField(
            model_name='facture',
            name='date_soumission',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de soumission'),
        ),
        migrations.AddField(
            model_name='facture',
            name='demandeur',
            field=models.ForeignKey(blank=True, db_column='demandeur_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_demandees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facture',
            name='numero_facture',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='N° de facture'),
        ),
        migrations.AddField(
            model_name='facture',
            name='priorite',
            field=models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('critical', 'Critique')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='facture',
            name='societe',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Société concernée'),
        ),
        migrations.RunPython(normalize_invoice_services, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='facture',
            name='echeance',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Échéance de paiement'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant',
            field=models.FloatField(null=True, verbose_name='Montant TTC (€)'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='service',
            field=models.CharField(blank=True, choices=[('developpement', 'Développement'), ('administratif', 'Administratif'), ('technique', 'Technique'), ('fonciere', 'Foncière'), ('financier', 'Financier')], default='', max_length=100),
        ),
    ]
