from django.urls import path
from .views import (
    admin_dossier_detail_view,
    admin_dossiers_export_view,
    admin_dossiers_import_view,
    admin_dossiers_view,
    admin_projects_view,
    administratif_view,
    send_reply_view,
    generate_auto_message_view,
    get_calendar_activities,
    create_activity_reminder_rule_view,
    create_activity_view,
    delete_activity_reminder_rule_view,
    delete_activity_view,
    get_calendar_activities_week,
    update_activity_view,
    create_project_view,
    update_project_view,
    delete_project_view,
    sync_gmail_journal_view,
    update_gmail_conversation_status,
    add_gmail_conversation_note,
)

app_name = 'management'

urlpatterns = [
    path('administratif/', administratif_view, name='admin'),
    path('administratif/dossiers/', admin_dossiers_view, name='admin_dossiers'),
    path('administratif/dossiers/export/', admin_dossiers_export_view, name='admin_dossiers_export'),
    path('administratif/dossiers/import/', admin_dossiers_import_view, name='admin_dossiers_import'),
    path('administratif/dossiers/<int:dossier_id>/', admin_dossier_detail_view, name='admin_dossier_detail'),
    path('administratif/projets/', admin_projects_view, name='admin_projects'),

    path('api/send-reply/', send_reply_view, name='send_reply'),
    path('api/generate-message/', generate_auto_message_view, name='generate_message'),
    path('api/gmail-journal/sync/', sync_gmail_journal_view, name='gmail_journal_sync'),
    path('api/gmail-journal/<int:conversation_id>/status/', update_gmail_conversation_status, name='gmail_journal_status'),
    path('api/gmail-journal/<int:conversation_id>/notes/', add_gmail_conversation_note, name='gmail_journal_note'),
    path('api/calendar-activities/', get_calendar_activities, name='calendar_activities'),
    path('api/activity-reminder-rules/create/', create_activity_reminder_rule_view, name='activity_reminder_rule_create'),
    path('api/activity-reminder-rules/<int:rule_id>/delete/', delete_activity_reminder_rule_view, name='activity_reminder_rule_delete'),
    path('api/delete-activity/', delete_activity_view, name='delete_activity'),
    path('api/create-activity/', create_activity_view, name='create_activity'),
    path('api/calendar-activities-week/', get_calendar_activities_week, name='calendar_activities_week'),
    path('api/update-activity/<str:activity_id>/', update_activity_view, name='update_activity'),
    path('api/admin-projects/create/', create_project_view, name='admin_project_create'),
    path('api/admin-projects/<int:project_id>/update/', update_project_view, name='admin_project_update'),
    path('api/admin-projects/<int:project_id>/delete/', delete_project_view, name='admin_project_delete'),
]
