# Generated by Django 5.2.8 on 2026-03-10 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Question')),
                ('response', models.TextField(verbose_name='Réponse')),
                ('query_type', models.CharField(choices=[('invoice', 'Facture'), ('legal', 'Juridique'), ('legal_fallback', 'Juridique fallback'), ('unknown', 'Inconnu')], default='unknown', max_length=20, verbose_name='Type de requête')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_queries', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Historique chatbot',
                'verbose_name_plural': 'Historique chatbot',
                'ordering': ['-created_at'],
            },
        ),
    ]
