# Generated by Django 5.2.8 on 2026-03-25 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotquery',
            name='sources',
            field=models.JSONField(blank=True, default=list, verbose_name='Sources'),
        ),
        migrations.AlterField(
            model_name='chatbotquery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Cree le'),
        ),
        migrations.AlterField(
            model_name='chatbotquery',
            name='query_type',
            field=models.CharField(choices=[('invoice', 'Facture'), ('document', 'Document interne'), ('legal', 'Juridique'), ('legal_fallback', 'Juridique fallback'), ('unknown', 'Inconnu')], default='unknown', max_length=20, verbose_name='Type de requete'),
        ),
        migrations.AlterField(
            model_name='chatbotquery',
            name='response',
            field=models.TextField(verbose_name='Reponse'),
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='Titre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis a jour le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Session chatbot',
                'verbose_name_plural': 'Sessions chatbot',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='chatbotquery',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queries', to='chatbot.chatsession', verbose_name='Session'),
        ),
    ]
