# Generated by Django 5.2.8 on 2026-03-03 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_column='reference', max_length=50, unique=True, verbose_name='Référence projet')),
                ('name', models.CharField(db_column='nom', max_length=255, verbose_name='Nom du projet')),
                ('type', models.TextField(choices=[('client', 'Client'), ('juridique', 'Juridique')], default='Client')),
                ('engaged_amount', models.DecimalField(db_column='frais_eng', decimal_places=2, default=0, max_digits=12, verbose_name='Frais engagés')),
                ('paid_amount', models.DecimalField(db_column='frais_payes', decimal_places=2, default=0, max_digits=12, verbose_name='Frais déjà payés')),
                ('total_estimated', models.DecimalField(db_column='total_estim', decimal_places=2, default=0, max_digits=12, verbose_name='Total estimé du projet')),
            ],
            options={
                'db_table': 'dossier',
            },
        ),
        migrations.CreateModel(
            name='DocumentTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projet', models.CharField(blank=True, max_length=255, verbose_name='Projet')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre du document')),
                ('type_document', models.CharField(choices=[('contrat_reservation', 'Contrat de réservation'), ('permis_construire', 'Permis de construire'), ('pv', 'Procès-verbal'), ('autre', 'Autre')], default='autre', max_length=50, verbose_name='Type de document')),
                ('fichier', models.FileField(upload_to='documents_tech/', verbose_name='Fichier')),
                ('texte_brut', models.TextField(blank=True, verbose_name='Texte extrait')),
                ('resume', models.TextField(blank=True, verbose_name='Résumé global')),
                ('prix', models.TextField(blank=True, verbose_name='Prix / montants')),
                ('dates', models.TextField(blank=True, verbose_name='Dates clés')),
                ('conditions_suspensives', models.TextField(blank=True, verbose_name='Conditions suspensives')),
                ('penalites', models.TextField(blank=True, verbose_name='Pénalités')),
                ('delais', models.TextField(blank=True, verbose_name='Délais')),
                ('clauses_importantes', models.TextField(blank=True, verbose_name='Clauses importantes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'db_table': 'document_technique',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Libellé')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Déjà payé')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Échéance')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='technique.technicalproject', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Frais projet',
                'verbose_name_plural': 'Frais projets',
                'db_table': 'depense_projet',
            },
        ),
    ]
