# Generated by Django 5.2.8 on 2026-03-16 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(
                    db_column='reference',
                    max_length=50,
                    unique=True,
                    verbose_name='Référence projet'
                )),
                ('name', models.CharField(
                    db_column='nom',
                    max_length=255,
                    verbose_name='Nom du projet'
                )),
                ('type', models.TextField(
                    choices=[('client', 'Client'), ('juridique', 'Juridique')],
                    default='client'
                )),
                ('engaged_amount', models.DecimalField(
                    db_column='frais_eng',
                    decimal_places=2,
                    default=0,
                    max_digits=12,
                    verbose_name='Frais engagés'
                )),
                ('paid_amount', models.DecimalField(
                    db_column='frais_payes',
                    decimal_places=2,
                    default=0,
                    max_digits=12,
                    verbose_name='Frais déjà payés'
                )),
                ('total_estimated', models.DecimalField(
                    db_column='total_estim',
                    decimal_places=2,
                    default=0,
                    max_digits=12,
                    verbose_name='Total estimé du projet'
                )),
            ],
            options={
                'db_table': 'dossier',
            },
        ),
        migrations.CreateModel(
            name='DocumentTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projet', models.CharField(blank=True, max_length=255, verbose_name='Projet')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre du document')),
                ('type_document', models.CharField(
                    choices=[
                        ('contrat_reservation', 'Contrat de réservation'),
                        ('permis_construire', 'Permis de construire'),
                        ('pv', 'Procès-verbal'),
                        ('autre', 'Autre')
                    ],
                    default='autre',
                    max_length=50,
                    verbose_name='Type de document'
                )),
                ('fichier', models.FileField(upload_to='documents_tech/', verbose_name='Fichier')),
                ('texte_brut', models.TextField(blank=True, verbose_name='Texte extrait')),
                ('resume', models.TextField(blank=True, verbose_name='Résumé global')),
                ('prix', models.TextField(blank=True, verbose_name='Prix / montants')),
                ('dates', models.TextField(blank=True, verbose_name='Dates clés')),
                ('conditions_suspensives', models.TextField(blank=True, verbose_name='Conditions suspensives')),
                ('penalites', models.TextField(blank=True, verbose_name='Pénalités')),
                ('delais', models.TextField(blank=True, verbose_name='Délais')),
                ('clauses_importantes', models.TextField(blank=True, verbose_name='Clauses importantes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('created_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Créé par'
                )),
            ],
            options={
                'db_table': 'document_technique',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Objet')),
                ('sender', models.CharField(max_length=255, verbose_name='Expéditeur')),
                ('recipients', models.TextField(blank=True, verbose_name='Destinataires')),
                ('cc', models.TextField(blank=True, verbose_name='Copie')),
                ('body', models.TextField(blank=True, verbose_name='Contenu')),
                ('received_at', models.DateTimeField(verbose_name='Reçu le')),
                ('has_attachments', models.BooleanField(default=False, verbose_name='Pièces jointes')),
                ('status', models.CharField(
                    choices=[
                        ('classified', 'Classé'),
                        ('pending', 'À valider'),
                        ('unassigned', 'Non classé')
                    ],
                    default='unassigned',
                    max_length=20,
                    verbose_name='Statut de classement'
                )),
                ('external_id', models.CharField(
                    blank=True,
                    max_length=255,
                    null=True,
                    verbose_name='Identifiant externe'
                )),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('imported_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='imported_technical_emails',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Importé par'
                )),
                ('project', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='emails',
                    to='technique.technicalproject',
                    verbose_name='Projet associé'
                )),
            ],
            options={
                'db_table': 'technical_email',
                'ordering': ['-received_at', '-id'],
                'constraints': [
                    models.UniqueConstraint(
                        fields=['external_id', 'imported_by'],
                        name='unique_email_per_user',
                        condition=models.Q(external_id__isnull=False),
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name='ProjectExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Libellé')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Déjà payé')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Échéance')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('project', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='expenses',
                    to='technique.technicalproject',
                    verbose_name='Projet'
                )),
            ],
            options={
                'verbose_name': 'Frais projet',
                'verbose_name_plural': 'Frais projets',
                'db_table': 'depense_projet',
                'ordering': ['due_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalEmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents_tech/emails/', verbose_name='Fichier')),
                ('original_name', models.CharField(max_length=255, verbose_name="Nom d'origine")),
                ('content_type', models.CharField(blank=True, max_length=150, verbose_name='Type MIME')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='Taille')),
                ('extracted_text', models.TextField(blank=True, verbose_name='Texte extrait')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('email', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='attachments',
                    to='technique.technicalemail',
                    verbose_name='Email'
                )),
                ('linked_document', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='source_attachments',
                    to='technique.documenttechnique',
                    verbose_name='Document technique lié'
                )),
            ],
            options={
                'db_table': 'technical_email_attachment',
                'ordering': ['id'],
            },
        ),
    ]