# Generated by Django 5.2.8 on 2026-05-21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technique", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TechnicalProjectHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("project_reference", models.CharField(blank=True, max_length=50, verbose_name="Référence projet")),
                ("project_name", models.CharField(blank=True, max_length=255, verbose_name="Nom du projet")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("project_created", "Projet créé"),
                            ("budget_updated", "Budget modifié"),
                            ("expense_created", "Dépense créée"),
                            ("expense_updated", "Dépense modifiée"),
                            ("expense_deleted", "Dépense supprimée"),
                            ("project_deleted", "Projet supprimé"),
                        ],
                        max_length=30,
                        verbose_name="Action",
                    ),
                ),
                ("target_type", models.CharField(max_length=50, verbose_name="Type de cible")),
                ("target_label", models.CharField(blank=True, max_length=255, verbose_name="Libellé cible")),
                ("before", models.JSONField(blank=True, default=dict, verbose_name="Avant")),
                ("after", models.JSONField(blank=True, default=dict, verbose_name="Après")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Créé le")),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history",
                        to="technique.technicalproject",
                        verbose_name="Projet",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="technical_project_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique projet technique",
                "verbose_name_plural": "Historiques projets techniques",
                "db_table": "historique_projet_technique",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
