# Generated by Django 5.2.8 on 2026-06-18 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technique', '0004_gmail_attachment_processing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectexpense',
            options={'ordering': ['due_date', 'id'], 'verbose_name': 'Frais dossier', 'verbose_name_plural': 'Frais dossiers'},
        ),
        migrations.AlterModelOptions(
            name='technicalprojecthistory',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Historique dossier technique', 'verbose_name_plural': 'Historiques dossiers techniques'},
        ),
        migrations.AlterModelOptions(
            name='technicalproject',
            options={'verbose_name': 'Dossier technique', 'verbose_name_plural': 'Dossiers techniques'},
        ),
        migrations.AlterField(
            model_name='documenttechnique',
            name='projet',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dossier'),
        ),
        migrations.AlterField(
            model_name='projectexpense',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='technique.technicalproject', verbose_name='Dossier'),
        ),
        migrations.AlterField(
            model_name='technicalemail',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='technique.technicalproject', verbose_name='Dossier associé'),
        ),
        migrations.AlterField(
            model_name='technicalproject',
            name='name',
            field=models.CharField(db_column='nom', max_length=255, verbose_name='Nom du dossier'),
        ),
        migrations.AlterField(
            model_name='technicalproject',
            name='reference',
            field=models.CharField(db_column='reference', max_length=50, unique=True, verbose_name='Référence dossier'),
        ),
        migrations.AlterField(
            model_name='technicalproject',
            name='total_estimated',
            field=models.DecimalField(db_column='total_estim', decimal_places=2, default=0, max_digits=12, verbose_name='Total estimé du dossier'),
        ),
        migrations.AlterField(
            model_name='technicalprojecthistory',
            name='action',
            field=models.CharField(choices=[('project_created', 'Dossier créé'), ('budget_updated', 'Budget modifié'), ('expense_created', 'Dépense créée'), ('expense_updated', 'Dépense modifiée'), ('expense_deleted', 'Dépense supprimée'), ('project_deleted', 'Dossier supprimé')], max_length=30, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='technicalprojecthistory',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='technique.technicalproject', verbose_name='Dossier'),
        ),
        migrations.AlterField(
            model_name='technicalprojecthistory',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom du dossier'),
        ),
        migrations.AlterField(
            model_name='technicalprojecthistory',
            name='project_reference',
            field=models.CharField(blank=True, max_length=50, verbose_name='Référence dossier'),
        ),
    ]
