# Generated by Codex on 2026-07-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technique", "0005_dossier_wording"),
    ]

    operations = [
        migrations.AddField(
            model_name="technicalproject",
            name="status",
            field=models.CharField(
                choices=[
                    ("etude", "Étude"),
                    ("promesse_signee", "Promesse signée"),
                    ("acquis", "Acquis"),
                ],
                db_column="statut",
                default="etude",
                max_length=30,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="technicalproject",
            name="type",
            field=models.TextField(
                choices=[
                    ("marchands_de_bien", "Marchands de bien"),
                    ("promotion", "Promotion"),
                    ("patrimoine", "Patrimoine"),
                ],
                default="marchands_de_bien",
                verbose_name="Type",
            ),
        ),
    ]
