# Generated by Codex on 2026-07-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technique", "0006_technicalproject_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technicalprojecthistory",
            name="action",
            field=models.CharField(
                choices=[
                    ("project_created", "Dossier créé"),
                    ("budget_updated", "Budget modifié"),
                    ("expense_created", "Dépense créée"),
                    ("expense_updated", "Dépense modifiée"),
                    ("expense_deleted", "Dépense supprimée"),
                    ("status_updated", "Statut modifié"),
                    ("project_deleted", "Dossier supprimé"),
                ],
                max_length=30,
                verbose_name="Action",
            ),
        ),
    ]
