# Generated by Django 5.2.8 on 2026-07-02 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technique', '0008_document_project_remove_document_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalprojecthistory',
            name='action',
            field=models.CharField(choices=[('project_created', 'Dossier créé'), ('budget_updated', 'Budget modifié'), ('expense_created', 'Dépense créée'), ('expense_updated', 'Dépense modifiée'), ('expense_deleted', 'Dépense supprimée'), ('key_date_created', 'Date clé créée'), ('key_date_updated', 'Date clé modifiée'), ('key_date_deleted', 'Date clé supprimée'), ('action_created', 'Action créée'), ('action_updated', 'Action modifiée'), ('action_deleted', 'Action supprimée'), ('status_updated', 'Statut modifié'), ('project_deleted', 'Dossier supprimé')], max_length=30, verbose_name='Action'),
        ),
        migrations.CreateModel(
            name='TechnicalProjectAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Action')),
                ('status', models.CharField(choices=[('todo', 'À faire'), ('in_progress', 'En cours'), ('done', 'Terminé'), ('cancelled', 'Annulé')], default='todo', max_length=20, verbose_name='Statut')),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('normal', 'Normale'), ('high', 'Haute'), ('urgent', 'Urgente')], default='normal', max_length=20, verbose_name='Priorité')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Échéance')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_actions_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_actions_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='technique.technicalproject', verbose_name='Dossier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_actions_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Action dossier technique',
                'verbose_name_plural': 'Actions dossiers techniques',
                'db_table': 'technical_project_action',
                'ordering': ['due_date', 'priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalProjectKeyDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Libellé')),
                ('date', models.DateField(verbose_name='Date')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('status', models.CharField(blank=True, choices=[('planned', 'Prévue'), ('done', 'Réalisée'), ('postponed', 'Reportée'), ('cancelled', 'Annulée')], max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_dates', to='technique.technicalprojectaction', verbose_name='Action liée')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_key_dates_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_dates', to='technique.documenttechnique', verbose_name='Document lié')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_dates', to='technique.technicalproject', verbose_name='Dossier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_key_dates_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Date clé dossier technique',
                'verbose_name_plural': 'Dates clés dossiers techniques',
                'db_table': 'technical_project_key_date',
                'ordering': ['date', 'id'],
            },
        ),
    ]
