"""
Django settings for DjangoProject project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from django.utils.encoding import force_str
import os
import environ
import logging


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Chargement .env
env = environ.Env()
env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = force_str(os.getenv('SECRET_KEY'))
SECRET_KEY_FALLBACKS = os.getenv('SECRET_KEY_FALLBACKS').split(',') or []
DEBUG = True
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_mailbox',
    'invoices',
    'django_filters',
    'chatbot',
    'management',
    'recrutement',
    'technique',
    'signatures',
    'django_celery_results',
    'django_celery_beat',
    'home',
    'authentication',
    # --- AJOUT A2F ---
    'django_otp',
    'django_otp.plugins.otp_static',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_email',
    'two_factor',
    'two_factor.plugins.phonenumber',
    'two_factor.plugins.email',
    'axes',
    'user_preferences',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # --- AJOUT AXES (Protection Brute Force) ---
    'axes.middleware.AxesMiddleware',

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    # --- AJOUT MIDDLEWARE AUDIT (Log Actions + IP) ---
    'config.middleware.AuditLogMiddleware',
    
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # --- AJOUT A2F ---
    'django_otp.middleware.OTPMiddleware',
    'two_factor.middleware.threadlocals.ThreadLocals',
]

AUTHENTICATION_BACKENDS = [
    # Axes doit être le PREMIER pour bloquer les intrus avant qu'ils ne testent le mot de passe
    'axes.backends.AxesStandaloneBackend',
    # backend de Django pour vérifier le mot de passe
    'django.contrib.auth.backends.ModelBackend',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates', 'invoices/templates', 'management/templates', 'chatbot/templates', 'recrutement/templates', "technique/templates", "signatures/templates"]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'home.context_processors.user_role_context',
                'user_preferences.context_processors.theme_context',
            ],
        },
    },
]

STATICFILES_DIRS = [
    BASE_DIR / "static",
    "chatbot/static",
    "management/static",
    "technique/static",

]

WSGI_APPLICATION = 'config.wsgi.application'


# Base de donnée
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB"),
        "USER": os.getenv("POSTGRES_USER"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
        "HOST": os.getenv("POSTGRES_HOST"),
        "PORT": os.getenv("POSTGRES_PORT"),
    }
}


# Valide mdp
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'Europe/Paris'
USE_I18N = True
USE_TZ = True

GROQ_API_KEY = env("GROQ_API_KEY")

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# url email
SITE_URL = env("SITE_URL", default="http://127.0.0.1:8000")

# Configuration a2f
LOGIN_URL = 'two_factor:login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = 'two_factor:login'

# "SE SOUVENIR DE MOI"
# 30 jours (en secondes)
TWO_FACTOR_REMEMBER_COOKIE_AGE = 60 * 60 * 24 * 30
TWO_FACTOR_REMEMBER_COOKIE_NAME = 'benjamin_intranet_device'
TWO_FACTOR_CALL_GATEWAY = None
TWO_FACTOR_SMS_GATEWAY = None
OTP_EMAIL_TOKEN_VALIDITY = 300  # Validité du code email en secondes (5 minutes)

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Configuration email pour les tests
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv("EMAIL_HOST")
# Port pour TLS
EMAIL_PORT = os.getenv("EMAIL_PORT")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")

# API LEGIFRANCE
LEGIFRANCE_CLIENT_ID = os.getenv("LEGIFRANCE_CLIENT_ID")
LEGIFRANCE_CLIENT_SECRET = os.getenv("LEGIFRANCE_CLIENT_SECRET")
# Configuration Celery - TOUT dans PostgreSQL
CELERY_BROKER_URL = 'sqla+postgresql://%(USER)s:%(PASSWORD)s@%(HOST)s:%(PORT)s/%(NAME)s' % DATABASES['default']
CELERY_RESULT_BACKEND = 'db+postgresql://%(USER)s:%(PASSWORD)s@%(HOST)s:%(PORT)s/%(NAME)s' % DATABASES['default']

# Alternative pour result_backend (utilise django-celery-results) :
# CELERY_RESULT_BACKEND = 'django-db'

# "sandbox" pour tester, "prod" quand ça sera bon
LEGIFRANCE_ENV = os.getenv("LEGIFRANCE_ENV", "sandbox")

CELERY_CACHE_BACKEND = 'django-cache'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Europe/Paris'
CELERY_ENABLE_UTC = True

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'my_cache_table',
    }
}


X_FRAME_OPTIONS = "SAMEORIGIN"

# --- CONFIGURATION AXES (Brute Force) ---
# Nombre d'échecs autorisés avant blocage
AXES_FAILURE_LIMIT = 5

# Durée du blocage en heures(10 minutes)
AXES_COOLOFF_TIME = 0.167

# Réinitialise le compteur si la connexion réussit
AXES_RESET_ON_SUCCESS = True

# Ici On bloque la combinaison ip + nom d'utilisateur
AXES_LOCKOUT_PARAMETERS = ["ip_address", ["username", "user_agent"]]
AXES_LOCKOUT_PARAMETERS = ["ip_address", "username"]
AXES_LOCKOUT_CALLABLE = 'authentication.axes_handlers.custom_lockout_response'
AXES_USERNAME_CALLABLE = 'authentication.axes_handlers.get_axes_username'
AXES_RESET_COOL_OFF_ON_FAILURE_DURING_LOCKOUT = False


# LOG 
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        # Obtenir toute les données
        'standard': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
        # Fichier nommé "AAAA-MM-JJ.log" 
        'daily_file': {
            'level': 'INFO', 
            'class': 'config.log_handlers.DailyDateFileHandler',
            'log_dir': BASE_DIR / 'logs',
            'formatter': 'standard',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        # Django
        'django': {
            'handlers': ['console', 'daily_file'],
            'level': 'INFO',
            'propagate': True,
        },
        # Sécurité
        'django.security': {
            'handlers': ['daily_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Axes
        'axes': {
            'handlers': ['daily_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Audit métier
        'audit': {
            'handlers': ['daily_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        }
    },
}



if os.getenv('DJANGO_ENV') == 'production':
    DEBUG = False
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # Permet de séccuriser les cookies
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # On empeche de faire des connexions http
    SECURE_HSTS_SECONDS = 31536000  # 1 an
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Permet de sécuriser les Hosts
    ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'benjamin-intranet.fr').split(',')
    
    print("\n🔒 MODE PRODUCTION ACTIVÉ : HTTPS forcé, Cookies sécurisés, Debug OFF.\n")
else:
    print("\n⚠️ MODE DÉVELOPPEMENT : HTTPS désactivé, Debug ON.\n")