# Generated by Django 5.2.8 on 2026-03-03 16:13

import django.db.models.deletion
import signatures.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to='documents/originaux/')),
                ('fichier_signe', models.FileField(blank=True, null=True, upload_to='documents/signes/')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('stamp_x', models.FloatField(blank=True, null=True)),
                ('stamp_y', models.FloatField(blank=True, null=True)),
                ('sig_x', models.FloatField(blank=True, null=True)),
                ('sig_y', models.FloatField(blank=True, null=True)),
                (
                    'signataire_requis',
                    models.CharField(
                        choices=[('CEO', 'CEO'), ('RH', 'RH')],
                        default='CEO',
                        max_length=10,
                    ),
                ),
            ],
            options={
                'db_table': 'document',
            },
        ),
        migrations.CreateModel(
            name='Tampon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Tampon officiel', max_length=200)),
                ('image', models.ImageField(upload_to='tampons/')),
            ],
            options={
                'db_table': 'tampon',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(
                    choices=[
                        ('upload', 'Document ajouté'),
                        ('en_attente', 'En attente de signature'),
                        ('signe', 'Signé'),
                        ('refuse', 'Refusé'),
                        ('erreur', 'Erreur')
                    ],
                    max_length=30
                )),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True)),
                ('document', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='historique',
                    to='signatures.document'
                )),
            ],
            options={
                'db_table': 'historique_signature',
            },
        ),
        migrations.CreateModel(
            name='SignatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_x_pct', models.FloatField()),
                ('pos_y_pct', models.FloatField()),
                ('statut', models.CharField(
                    choices=[
                        ('pending', 'En attente'),
                        ('approved', 'Approuvée'),
                        ('refused', 'Refusée'),
                        ('expired', 'Expirée')
                    ],
                    default='pending',
                    max_length=20
                )),
                ('token', models.CharField(
                    default=signatures.models.generate_signature_token,
                    max_length=64,
                    unique=True
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('commentaire_ceo', models.TextField(blank=True)),
                ('approver', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='signatures_demandes_a_valider',
                    to=settings.AUTH_USER_MODEL
                )),
                ('document', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='demandes_signature',
                    to='signatures.document'
                )),
                ('requested_by', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='signatures_demandes_emises',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'db_table': 'demande_signature',
            },
        ),
        migrations.CreateModel(
            name='SignatureUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='signatures/')),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='signature_profile',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'db_table': 'signature_utilisateur',
            },
        ),
    ]